#!/bin/sh
# Summary: Run all tests. Requires that your /etc/hosts file has an entry for
#   your docker machine with the name `dockerhost`.

# use parens here to prevent exporting variable to parent env
(
  export ELASTICSEARCH_HOST=dockerhost
  py.test "$@"
)
